sonar.projectKey=world-cup-hub-backend
sonar.organization=nikotpab

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=World Cup Hub Backend
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app
sonar.tests=tests

# Language
sonar.language=py
sonar.python.version=3.11

# Coverage
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/*.html,**/*.css,**/*.js,**/tests/**,**/migrations/**
