name: Test Dispatch
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI is alive"
